# Generated by Django 4.2.2 on 2023-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Participant_name',
            new_name='participant',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('momo', 'Mono')], max_length=10),
        ),
    ]
