# Generated by Django 4.2.2 on 2023-07-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
