# Generated by Django 4.2.2 on 2023-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_end_time_schedule_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['id'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
